// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const rawSupabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_URL = rawSupabaseUrl.startsWith('/') 
  ? `${window.location.origin}${rawSupabaseUrl}`
  : rawSupabaseUrl;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const HAS_SUPABASE_CONFIG = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!HAS_SUPABASE_CONFIG) {
  console.error(
    'Supabase env vars are missing. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in Vercel project settings.',
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  HAS_SUPABASE_CONFIG ? SUPABASE_URL : (typeof window !== 'undefined' ? window.location.origin : 'http://localhost'),
  HAS_SUPABASE_CONFIG ? SUPABASE_PUBLISHABLE_KEY : 'missing-supabase-key',
  {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Developer Sandbox Bypass Interceptor
const authAny = supabase.auth as any;
const originalGetUser = authAny.getUser.bind(authAny);
authAny.getUser = async (token?: string) => {
  const sandboxUserStr = typeof window !== 'undefined' ? localStorage.getItem('nyra_sandbox_user') : null;
  if (sandboxUserStr) {
    try {
      const user = JSON.parse(sandboxUserStr);
      return { data: { user }, error: null };
    } catch (e) {
      console.error('Failed to parse sandbox user:', e);
    }
  }
  return originalGetUser(token);
};

const originalGetSession = authAny.getSession.bind(authAny);
authAny.getSession = async () => {
  const sandboxUserStr = typeof window !== 'undefined' ? localStorage.getItem('nyra_sandbox_user') : null;
  if (sandboxUserStr) {
    try {
      const user = JSON.parse(sandboxUserStr);
      return {
        data: {
          session: {
            access_token: 'sandbox-token-12345',
            refresh_token: 'sandbox-refresh-12345',
            expires_in: 3600,
            token_type: 'bearer',
            user,
          }
        },
        error: null
      };
    } catch (e) {
      console.error('Failed to parse sandbox session:', e);
    }
  }
  return originalGetSession();
};

const originalSignOut = authAny.signOut.bind(authAny);
authAny.signOut = async (options?: any) => {
  if (typeof window !== 'undefined') {
    localStorage.removeItem('nyra_sandbox_user');
  }
  return originalSignOut(options);
};

const originalOnAuthStateChange = authAny.onAuthStateChange.bind(authAny);
authAny.onAuthStateChange = (callback: any) => {
  const sandboxUserStr = typeof window !== 'undefined' ? localStorage.getItem('nyra_sandbox_user') : null;
  if (sandboxUserStr) {
    try {
      const user = JSON.parse(sandboxUserStr);
      const session = {
        access_token: 'sandbox-token-12345',
        refresh_token: 'sandbox-refresh-12345',
        expires_in: 3600,
        token_type: 'bearer',
        user,
      };
      
      // Trigger callback with simulated signed in event immediately
      setTimeout(() => {
        callback('SIGNED_IN', session);
      }, 0);

      return {
        data: {
          subscription: {
            unsubscribe: () => {}
          }
        }
      };
    } catch (e) {
      console.error('Failed to parse sandbox session in onAuthStateChange:', e);
    }
  }
  return originalOnAuthStateChange(callback);
};